fix jenkins

diff --git a/library/kubedog/0.13.0/Dockerfile b/library/kubedog/0.13.0/Dockerfile
--- a/library/kubedog/0.13.0/Dockerfile
+++ b/library/kubedog/0.13.0/Dockerfile
@@ -8,22 +8,22 @@ ARG uid=1000
 ARG gid=1000
 
 RUN set -eux; \
-      apt-get update; \
-      groupadd -g ${gid} ${group}; \
-      useradd -u ${uid} -g ${gid} -l -m -s /bin/bash ${user}; \
-      arch="$(dpkg --print-architecture)"; arch="${arch##*-}"; \
-      case "$arch" in \
-          'amd64') \
-              url="https://tuf.kubedog.werf.io/targets/releases/${KUBEDOG_VERSION}/linux-${arch}/bin/kubedog"; \
-              ;; \
-          'arm64') \
-              url="https://tuf.kubedog.werf.io/targets/releases/${KUBEDOG_VERSION}/linux-${arch}/bin/kubedog"; \
-              ;; \
-          *) \
-              echo >&2 "error: unsupported architecture '$arch' (likely packaging update needed)"; exit 1 ;; \
-      esac; \
-      curl -fsSL -o /usr/bin/kubedog $url; \
-      chmod 755 /usr/bin/kubedog; \
-      kubedog version
+        apt-get update; \
+        groupadd -g ${gid} ${group}; \
+        useradd -u ${uid} -g ${gid} -l -m -s /bin/bash ${user}; \
+        arch="$(dpkg --print-architecture)"; arch="${arch##*-}"; \
+        case "$arch" in \
+            'amd64') \
+                url="https://tuf.kubedog.werf.io/targets/releases/${KUBEDOG_VERSION}/linux-${arch}/bin/kubedog"; \
+                ;; \
+            'arm64') \
+                url="https://tuf.kubedog.werf.io/targets/releases/${KUBEDOG_VERSION}/linux-${arch}/bin/kubedog"; \
+                ;; \
+            *) \
+                echo >&2 "error: unsupported architecture '$arch' (likely packaging update needed)"; exit 1 ;; \
+        esac; \
+        curl -fsSL -o /usr/bin/kubedog $url; \
+        chmod 755 /usr/bin/kubedog; \
+        kubedog version
 
 USER jenkins
